//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport.API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [KnownType(typeof(Phase))]
    [KnownType(typeof(Project))]
    [KnownType(typeof(Status))]
    public partial class Execution
    {
        public int id { get; set; }
        public string testName { get; set; }
        public int idStatus { get; set; }
        public int idPhase { get; set; }
        public int idProject { get; set; }
        public string executionTime { get; set; }
        public System.DateTime executionDate { get; set; }
    
        public Phase Phase { get; set; }
        public Project Project { get; set; }
        public Status Status { get; set; }
    }
}
