//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Execution
    {
        public int id { get; set; }
        public string testName { get; set; }
        public int idStatus { get; set; }
        public int idPhase { get; set; }
        public System.TimeSpan executionTime { get; set; }
        public System.DateTime executionDate { get; set; }
        public Nullable<int> idProject { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
    }
}
